version: '3.1'

services: 
    web:
        container_name: webserver
        build: 
            context: ./webserver/php
        volumes: 
            - ./src:/var/www/html/
        ports: 
            - "8080:80"
        depends_on: 
           - db
        links: 
            - db


    db:
        image: mariadb
        container_name: mariadb
        volumes: 
            - ./mysql:/var/lib/mysql
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: test
    
    adminer:
        container_name: adminer
        image: adminer
        ports: 
            - 4444:8080
        depends_on: 
            - db
        links: 
            - db
